name: Update Changelog Test
on: push

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: main

            - name: Update Changelog2
              uses: stefanzweifel/changelog-updater-action@v1
              with:
                  release-notes: ${{ github.event.release.body }}
                  latest-version: ${{ github.event.release.name }}

            - name: Commit updated CHANGELOG
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: main
                  commit_message: Update CHANGELOG
                  file_pattern: CHANGELOG.md