name: Update Changelog
on:
  release:
    types: [published]

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: main
            - name: "Build Changelog"
                id: build_changelog
                uses: mikepenz/release-changelog-builder-action@{latest-release}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Update Changelog2
              uses: stefanzweifel/changelog-updater-action@v1
              with:
                  release-notes: ${{steps.build_changelog.outputs.changelog}}
                  latest-version: ${{ github.event.release.name }}

            - name: Commit updated CHANGELOG
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: main
                  commit_message: Update CHANGELOG
                  file_pattern: CHANGELOG.md