name: Create Archive
  on:
    push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig .github/* phpcs.xml .gitignore'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
