name: On release
on:
    release:
        types: [released]
jobs:
  resources:
    name: Update wp plugin version
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4

        - name: Update version
          run: python ./.github/workflows/update_version.py ${{ github.event.release.name }}

        - name: Update wp plugin version
          uses: test-room-7/action-update-file@v1
          with:
              file-path: |
                sim-plugin.php
                CHANGELOG.md
              commit-msg: Update wp plugin version
              github-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Zip Folder
          run: zip -r ${{ github.event.repository.name }}.zip . -x "*/simNigeria/*" "*/signal/*" ".git/*" ".github/*" "phpcs.xml" "composer.json" "composer.lock" ".gitignore" "signalbot.db" "SignalBot.py" "CHANGELOG.md" "README.md" "*.code-workspace" "*.cmd" "test.php"

        - name: Release
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: ${{ github.event.repository.name }}.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}