name: Update Plugin Version
on:
    release:
        types: [released]
jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1

        - uses: actions/setup-node@v1

        - name: Update version
          run: python ./.github/workflows/update_version.py ${{ github.event.release.name }}

        - name: Modifiy the specific files using action
        -  uses: action-owner/action-repo@ref
          - name: Commit and push changes
            run: |
              git config --global user.name "tjippy"
              git config --global user.email "ewaldha@hotmail.com"

              git add -A
              git commit -m "commit message"
              git push